package com.project.code.Model;

import jakarta.persistence.Id;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.NotNull;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "reviews")
public class Review {

// 1. Add 'customerId' field:
//    - Type: private Long
//    - This field represents the customer who created the review.
//    - This field cannot be empty, use the @NotNull annotation to enforce this rule.

// 2. Add 'productId' field:
//    - Type: private Long
//    - This field represents the product being reviewed.
//    - This field cannot be empty, use the @NotNull annotation to enforce this rule.

// 3. Add 'storeId' field:
//    - Type: private Long
//    - This field represents the store associated with the product.
//    - This field cannot be empty, use the @NotNull annotation to enforce this rule.

// 4. Add 'rating' field:
//    - Type: private Integer
//    - This field represents the rating given to the product (out of 5).
//    - This field cannot be empty, use the @NotNull annotation to enforce this rule.

// 5. Add 'comment' field:
//    - Type: private String
//    - This field represents an optional comment on the product.

// 6. Add validation:
//    - Apply @NotNull to the customerId, productId, storeId, and rating fields to ensure they are not null.
//    - Example: @NotNull(message = "Customer cannot be null")

// 7. Add @Document annotation:
//    - Use @Document(collection = "reviews") to indicate that this class represents a MongoDB document.

// 8. Add constructor:
//    - The constructor should accept values for customerId, productId, storeId, rating, and an optional comment.

// 9. Add @Id annotation:
//    - Use @Id to mark the field 'id' as the primary key for MongoDB.
//    - The 'id' field is of type String and will be automatically generated by MongoDB.

// 10. Add Getters and Setters:
//    - Add getter and setter methods for all fields (customerId, productId, storeId, rating, comment).

    @Id
    private String id;
    @NotNull(message="Customer cannot be null")
    private long customerId;
    @NotNull(message = "Product cannot be null")
    private long productId;
    @NotNull (message="Store cannot be null")
    private long storeId;
    @NotNull(message = "Rating cannot be null")
    @Max(value=5)
    private int rating;
    private String comment;

    public Review(long customerId, long productId, long storeId, int rating) {
        this.customerId = customerId;
        this.productId = productId;
        this.storeId = storeId;
        this.rating = rating;
    }

    public Review(long customerId, long productId, long storeId, int rating, String comment) {
        this.customerId = customerId;
        this.productId = productId;
        this.storeId = storeId;
        this.rating = rating;
        this.comment = comment;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }

    public long getProductId() {
        return productId;
    }

    public void setProductId(long productId) {
        this.productId = productId;
    }

    public long getStoreId() {
        return storeId;
    }

    public void setStoreId(long storeId) {
        this.storeId = storeId;
    }

    public int getRating() {
        return rating;
    }

    public void setRating(int rating) {
        this.rating = rating;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }
}
